name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - develop
      - release/*
      - feature/*
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: |
          npm install

      - name: Build
        run: |
          npm run build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Run Tests
        run: |

  package:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Package
        run: |

      - name: Set Git Bot
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Update local branch
        run: |
          git pull origin ${BRANCH_NAME} --rebase

      - name: Version handling
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=$(node -p "require('./package.json').version")

          if [[ "$BRANCH_NAME" == "master" ]]; then
            npm version minor
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            npm version prerelease --preid=dev
          elif [[ "$BRANCH_NAME" =~ ^feature/ ]]; then
            echo "Feature branch $BRANCH_NAME was pushed. Version remains at $VERSION."
            exit 0
          fi

          git push origin $BRANCH_NAME

  deploy_release:
    needs: package
    runs-on: ubuntu-latest
    environment:
      name: Release Deployment
    permissions:
      packages: write
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Set Git Bot
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Create and Push Release Branch
        run: |
          git pull
          npm version patch
          VERSION=$(node -p "require('./package.json').version")
          RELEASE_BRANCH="release/${VERSION}"

          git checkout -b ${RELEASE_BRANCH} 2>/dev/null || git checkout -b ${RELEASE_BRANCH}
          git push origin ${RELEASE_BRANCH}
