name: Versioning and Release Branch Creation

on:
  push:
    branches:
      - master
      - develop
      - feature/*

jobs:
  notify:
    if: github.event_name == 'push' && github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - run: echo "New changes detected in develop. You can now manually trigger a release deployment from the GitHub Actions tab."

  versioning:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Set Git User
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Version handling logic and push to release
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          VERSION=$(node -p "require('./package.json').version")

          if [[ "$BRANCH_NAME" == "master" ]]; then
            npm version minor
          elif [[ "$BRANCH_NAME" == "develop" ]]; then
            npm version prerelease --preid=dev
          elif [[ "$BRANCH_NAME" =~ ^feature/ ]]; then
            echo "Feature branch $BRANCH_NAME was pushed. Version remains at $VERSION."
            exit 0
          fi

          # Update version on the original branch before switching
          git push origin $BRANCH_NAME

          # Create a new release branch or switch to it if it already exists
          git checkout -b release-${VERSION} 2>/dev/null || git checkout release-${VERSION}

          # Push the release branch
          git push origin release-${VERSION}
